### ISSUE TITLE
[BUG]多次运行下载文件下载多次会出现卡死的情况

### ISSUE THREAD

**Issue by ZhouBoAdmin** [ldqk0/Masuit.Tools#5]
**bug描述**

**是哪个函数出现了bug**

**异常堆栈信息**

**函数入参**

**期望的结果或输出**

**使用环境:**
 - .NET Runtime [e.g. 6.0]

**您的一些其他的想法**

**Comment by ldqk** [comment]
请提供下你的调用代码

**Comment by ZhouBoAdmin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ldqk0/Masuit.Tools] [BUG]多次运行下载文件下载多次会出现卡死的情况 (Issue #5)





 
请提供下你的调用代码
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhouBoAdmin** [comment]
![1647507601](https://user-images.githubusercontent.com/51780846/158774043-c161d0af-2a26-4d25-a857-91737d548b35.png)

**Comment by ldqk** [comment]
详细的堆栈信息粘贴下，我目前尚未复现这个错误

**Comment by ZhouBoAdmin** [comment]
在 System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   在 Masuit.Tools.Net.MultiThreadDownloader.get_TotalSpeedInBytes()
   在 Program.<>c.<<Main>$>b__0_1(Object sender, EventArgs e) 在 C:\Users\Administrator\Desktop\ConsoleApp1\ConsoleApp1\Program.cs 中: 第 13 行
   在 Masuit.Tools.Net.MultiThreadDownloader.<UpdateProgress>b__52_0(Object state)
   在 System.Threading.SynchronizationContext.<>c.<Post>b__8_0(ValueTuple`2 s)
   在 System.Threading.QueueUserWorkItemCallbackDefaultContext`1.Execute()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   在 System.Threading.Thread.StartCallback()

**Comment by ldqk** [comment]
已修正，更新最新包即可。
